import {validateKit,jobIdentity,approvalFor,assertApproval} from './core.mjs';
import {pageBridge} from './page-bridge.mjs';
const $=id=>document.getElementById(id),notice=s=>$('notice').textContent=s;
let kit,job,tabId,review,busy=false;
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('summer27-helper',2);r.onupgradeneeded=()=>{for(const name of ['kits','events','meta','claims'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
function transaction(store,mode,fn){return new Promise((resolve,reject)=>{const t=db.transaction(store,mode),r=fn(t.objectStore(store));let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Local save interrupted.'));});}
const get=(s,k)=>transaction(s,'readonly',o=>o.get(k)),put=(s,k,v)=>transaction(s,'readwrite',o=>o.put(v,k)),all=s=>transaction(s,'readonly',o=>o.getAll());
function claimAttempt(event){return new Promise((resolve,reject)=>{const tx=db.transaction(['claims','events'],'readwrite');tx.objectStore('claims').add({id:event.id,at:event.at},event.jobKey);tx.objectStore('events').add(event,event.id);tx.oncomplete=resolve;tx.onabort=()=>reject(Error('This job already has a submission attempt. Check the employer receipt before proceeding manually.'));tx.onerror=()=>{};});}
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function details(parent,rows){parent.replaceChildren();const dl=document.createElement('dl');for(const [label,value] of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);dl.append(dt,dd);}parent.append(dl);}
function invalidate(){review=null;$('review').hidden=true;$('submit-consent').checked=false;$('submit').disabled=true;}
async function refreshJob(){invalidate();$('receipt-consent').checked=false;$('receipt-note').value='';job=kit?.jobs.find(j=>j.jobKey===$('job').value);$('prepare-consent').checked=false;if(!job)return;details($('destination'),[['雇主',job.company],['岗位',job.title],['申请页面',job.url]]);const events=(await all('events')).filter(e=>e.jobKey===job.jobKey);$('receipt').hidden=!events.some(e=>e.status==='attempted');$('prepare').disabled=events.some(e=>['attempted','confirmed'].includes(e.status));$('inspect').disabled=$('prepare').disabled;if($('prepare').disabled)notice('这份申请已有提交尝试记录。请核实回执；助手不会再次提交。');}
async function showKit(){if(!kit)return;$('workspace').hidden=false;$('job').replaceChildren();for(const j of kit.jobs){const o=document.createElement('option');o.value=j.jobKey;o.textContent=`${j.company} · ${j.title}`;$('job').append(o);}const [tab]=await chrome.tabs.query({active:true,currentWindow:true});tabId=tab?.id;const current=jobIdentity(tab?.url),previous=await get('meta','lastJob');if(kit.jobs.some(j=>j.jobKey===current))$('job').value=current;else if(kit.jobs.some(j=>j.jobKey===previous))$('job').value=previous;details($('kit-details'),[...Object.entries(kit.profile).filter(([,v])=>v),['简历',`${kit.resume.name} · ${kit.resume.size} bytes · SHA-256 ${kit.resume.sha256}`],...kit.answers.map(a=>[a.question,a.answer])]);await refreshJob();}
async function run(action,extra={}){if(!job||!tabId)throw Error('Open the employer application page and click this extension again.');const results=await chrome.scripting.executeScript({target:{tabId},func:pageBridge,args:[action,{job,expectedResume:{name:kit.resume.name,sha256:kit.resume.sha256},...extra}]});if(!results[0]?.result)throw Error('No form result. Reopen the full application page and invoke the extension there.');return results[0].result;}
async function withBusy(fn){if(busy)return;busy=true;$('job').disabled=true;$('import').disabled=true;try{await fn();}catch(e){notice(e.message||String(e));invalidate();}finally{busy=false;$('job').disabled=false;$('import').disabled=false;}}
$('import').onchange=()=>withBusy(async()=>{const f=$('import').files[0];if(!f)return;if(f.size>5*1024*1024)throw Error('申请包过大。');const next=validateKit(JSON.parse(await f.text()));const bytes=Uint8Array.from(atob(next.resume.base64),c=>c.charCodeAt(0));const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');if(hash!==next.resume.sha256||bytes.length!==next.resume.size)throw Error('简历校验失败，请重新导出申请包。');const id=crypto.randomUUID();await put('kits',id,next);await put('meta','activeKit',id);kit=next;await showKit();notice('申请包已保存在本机浏览器。先打开岗位的完整申请表单，再点击助手。');});
$('job').onchange=()=>{if(busy){$('job').value=job?.jobKey||'';return;}return withBusy(refreshJob);};
$('open').onclick=()=>withBusy(async()=>{await put('meta','lastJob',job.jobKey);await chrome.tabs.create({url:job.url});notice('在新标签页打开完整申请表单，然后再次点击扩展图标。');});
$('prepare').onclick=()=>withBusy(async()=>{invalidate();if(!$('prepare-consent').checked)throw Error('请先确认本次资料可以传到雇主页面。');const r=await run('prepare',{kit});notice(`已预填 ${r.filled.length} 项，尚未提交。\n${r.filled.join('\n')}\n${r.skipped.join('\n')}\n请完成原站剩余问题和验证码后，重新读取表单。`);});
$('inspect').onclick=()=>withBusy(async()=>{invalidate();review=await run('inspect');$('review').hidden=false;details($('review-details'),[['雇主 / 岗位',`${job.company} · ${job.title}`],['原站标题',review.title],['地址',review.url],['表单提交目标',review.action],...review.fields.map(f=>[`${f.label}${f.required?'（必填）':''}`,f.value]),['原站提交按钮',review.submitLabel]]);$('blockers').textContent=review.blockers.join('\n');notice(review.blockers.length?'请在原页处理以上项目，再重新读取。':'请逐项核对全部答案和附件。');});
$('submit-consent').onchange=()=>{$('submit').disabled=!$('submit-consent').checked||!review||review.blockers.length>0;};
$('submit').onclick=()=>withBusy(async()=>{if(!$('submit-consent').checked||!review)throw Error('请先核对并确认本次申请。');const approval=approvalFor(review,Date.parse(review.reviewedAt));const fresh=await run('inspect');assertApproval(fresh,approval);const past=(await all('events')).filter(e=>e.jobKey===job.jobKey);if(past.some(e=>['attempted','confirmed'].includes(e.status)))throw Error('此岗位已有提交尝试。请核实原站结果，不自动重复提交。');const event={id:crypto.randomUUID(),jobKey:job.jobKey,url:job.url,company:job.company,title:job.title,at:new Date().toISOString(),status:'attempted',resumeName:kit.resume.name,formHash:review.hash,receipt:'User approved this exact form; submission outcome requires employer receipt.'};await claimAttempt(event);await put('meta','lastJob',job.jobKey);invalidate();try{await run('submit',{approval});notice('已点击雇主的提交按钮。请检查成功页面或邮件；尚未标记为申请成功。');}catch(e){notice(`提交结果未确认：${e.message}。请检查原站，助手不会自动重试。`);}await refreshJob();});
$('confirm-receipt').onclick=()=>withBusy(async()=>{if(!$('receipt-consent').checked||!$('receipt-note').value.trim())throw Error('请确认你已看到回执，并填写回执说明。');const attempt=(await all('events')).find(e=>e.jobKey===job.jobKey&&e.status==='attempted');if(!attempt)throw Error('这个岗位没有提交尝试记录。');const e={id:crypto.randomUUID(),attemptId:attempt.id,jobKey:job.jobKey,url:job.url,company:job.company,title:job.title,at:new Date().toISOString(),status:'confirmed',userConfirmedReceipt:true,resumeName:attempt.resumeName,receipt:$('receipt-note').value.trim().slice(0,1000)};await put('events',e.id,e);$('receipt-consent').checked=false;$('receipt-note').value='';notice('回执已记录。导出后在工作台的 Application desk 导入，投递进度才会同步。');});
$('export').onclick=()=>withBusy(async()=>download('summer27-application-events.json',{kind:'summer27-application-events',schemaVersion:1,exportedAt:new Date().toISOString(),events:await all('events')}));
try{const id=await get('meta','activeKit');kit=id?await get('kits',id):null;await showKit();}catch(e){notice(e.message);}
