'use client';
import {useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Download,Upload,Check,FileCheck2} from 'lucide-react';
import {platformFor,makeApplicationKit,isSensitiveQuestion,importApplicationEvents} from '@/lib/application-flow.mjs';

export function ApplicationDesk({data,jobs,setData,onOpen,onUpdate,message}){
 const [query,setQuery]=useState(''),[onlyQueue,setOnlyQueue]=useState(false),[smallOnly,setSmallOnly]=useState(false),[page,setPage]=useState(1),[resume,setResume]=useState(null),[factsReviewed,setFactsReviewed]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('');
 const receiptFile=useRef(null),latest=useRef(data),answers=data.applicationAnswers||[];latest.current=data;
 const queued=jobs.filter(j=>!j.duplicateOf&&j.application?.queued);
 const candidates=useMemo(()=>jobs.filter(j=>!j.duplicateOf&&(onlyQueue?j.application?.queued:platformFor(j.url)&&j.scopeStatus!=='outside-target'&&j.year===2027&&j.season==='Summer'&&['US','USA','United States'].includes(j.country)&&!['unlisted','closed'].includes(j.sourceState))).filter(j=>(!onlyQueue||j.application?.queued)&&(!smallOnly||j.application?.companySize==='Small / startup')&&`${j.company} ${j.title}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(!!b.application?.queued)-Number(!!a.application?.queued)||(b.match?.score??-1)-(a.match?.score??-1)),[jobs,query,onlyQueue,smallOnly]);
 function save(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
 async function chooseResume(e){try{const f=e.target.files?.[0];if(!f)return;setFactsReviewed(false);if(!/\.(pdf|docx)$/i.test(f.name)||f.size>3*1024*1024||!f.size)throw Error('请选择不超过 3 MB 的 PDF 或 DOCX 简历。');const bytes=new Uint8Array(await f.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const digest=await crypto.subtle.digest('SHA-256',bytes);setResume({name:f.name,type:f.name.toLowerCase().endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document',size:f.size,base64:btoa(binary),sha256:[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('')});}catch(e){message(e);} }
 function exportKit(){try{const kit=makeApplicationKit({profile:data.profile,jobs:queued,resume,answers,factsReviewed});save('summer27-application-kit.json',kit);message('申请包已导出。导入浏览器扩展后逐份预填、逐份确认提交；此处没有向雇主发送任何资料。');}catch(e){message(e);}}
 return <><div className="sectionhead"><div><p className="eyebrow">SMALL COMPANY APPLICATIONS</p><h2>准备成批做，提交逐份确认。</h2><p className="muted">Ashby · Greenhouse · Lever。队列、联系方式、简历和答案复用；日常预填无需模型调用。</p></div><a className="primary" href="/summer27-application-helper.zip" download><Download size={17}/>下载 Chrome / Edge 助手</a></div>
 <div className="application-steps"><span><b>1</b>选岗入队</span><span><b>2</b>导出指定材料</span><span><b>3</b>确认预填与上传</span><span><b>4</b>逐份核对后提交</span><span><b>5</b>导入雇主回执</span></div>
 <div className="notice"><FileCheck2 size={20}/><span>首次使用需在 Chrome 或 Edge 安装本地扩展。<a href="/application-helper-guide.html" target="_blank" rel="noreferrer">查看三步安装说明</a>。Codex 内置浏览器不等于 Chrome / Edge 扩展环境；未知控件、登录和验证码在雇主页面完成。</span></div>
 <div className="application-layout"><section className="panel"><h3>选择这批申请</h3><p className="muted smalltext">使用这些招聘平台不代表公司规模小。只有你标记为 Small / startup 的公司才进入“小公司”筛选。</p><input className="desk-search" aria-label="搜索待申请公司" placeholder="搜索公司或职位" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><div className="actions spaced"><label className="inlinecheck"><input type="checkbox" checked={onlyQueue} onChange={e=>{setOnlyQueue(e.target.checked);setPage(1);}}/>只看队列</label><label className="inlinecheck"><input type="checkbox" checked={smallOnly} onChange={e=>{setSmallOnly(e.target.checked);setPage(1);}}/>只看已标记的小公司</label><b>{queued.length} 个已入队</b></div>
 <div className="desk-jobs">{candidates.slice((page-1)*15,page*15).map(j=>{const applied=['Applied','OA received','OA completed','Interview','Offer'].includes(j.status),blocked=j.match?.eligibility==='blocked';return <article className="desk-job" key={j.id}><div><button className="jobtitle" onClick={()=>onOpen(j.id)}>{j.company} · {j.title}</button><div className="tags"><span>{platformFor(j.url)||'Manual platform'}</span><span>{j.application?.companySize||'Size unknown'}</span><span>{j.status}</span>{blocked&&<span className="badtag">资格冲突</span>}</div><small className="muted">{j.location}</small><label className="smalltext">公司规模（你确认）<select value={j.application?.companySize||'Unknown'} onChange={e=>onUpdate(j.id,{application:{...j.application,companySize:e.target.value,at:new Date().toISOString()}})}><option>Unknown</option><option>Small / startup</option><option>Mid-size</option><option>Large</option></select></label></div><button className={j.application?.queued?'secondary':'primary'} disabled={!j.application?.queued&&(applied||blocked)} onClick={()=>onUpdate(j.id,{application:{...j.application,queued:!j.application?.queued,at:new Date().toISOString()}})}>{j.application?.queued?'移出本批队列':'加入队列'}</button></article>;})}</div>{!candidates.length&&<p className="muted">没有符合当前筛选的岗位。可调整关键词，或在 JD studio 导入新的雇主链接。</p>}<div className="actions spaced"><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(candidates.length/15))} · {candidates.length} 个</span><button className="secondary" disabled={page*15>=candidates.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div></section>
 <aside><section className="panel"><span className="eyebrow">APPLICATION KIT</span><h3>一份简历，对应这一批岗位</h3><p>每包最多 20 个岗位；按 AIE、MLE、SDE 简历版本分批。扩展会保存导入的申请包，下次可继续使用。</p><label>选定实际简历<input type="file" accept=".pdf,.docx" onChange={chooseResume}/></label>{resume&&<p className="muted smalltext">{resume.name} · {Math.round(resume.size/1024)} KB<br/>只进入你导出的申请包，不上传到求职系统服务器。</p>}<p className="smalltext">联系人：{data.profile.name} · {data.profile.email||'请先在 My evidence 填写邮箱'}</p><label className="inlinecheck spaced"><input type="checkbox" checked={factsReviewed} onChange={e=>setFactsReviewed(e.target.checked)}/>我已核对所选简历和联系方式，处理或接受已提示的 事实差异，并逐岗检查资格</label><button className="primary spaced" disabled={!queued.length||!resume||!factsReviewed} onClick={exportKit}><Download size={16}/>导出 {queued.length} 个岗位的申请包</button><p className="muted smalltext">申请包含个人资料和完整简历，仅导入你安装的助手。导出不是批准投递；扩展会分别询问预填上传与最终提交。</p></section>
 <section className="panel spaced"><h3>完全相同的问题，复用你的答案</h3><p className="muted smalltext">只按完整题目匹配。授权、赞助、薪资、敏感资料、同意条款和公司专属动机不会自动填写。</p><label>雇主的完整题目<input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="例如：Link to your portfolio"/></label><label>你认可的答案<textarea rows={3} value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="secondary spaced" disabled={!question.trim()||!answer.trim()||isSensitiveQuestion(question)||answers.length>=30} onClick={()=>{setData(d=>({...d,applicationAnswers:[...(d.applicationAnswers||[]).filter(a=>a.question.trim().toLowerCase()!==question.trim().toLowerCase()),{question:question.trim(),answer:answer.trim()}]}));setQuestion('');setAnswer('');}}>保存供下一次复用</button>{isSensitiveQuestion(question)&&<p className="danger smalltext">这类问题需在每份雇主申请表上亲自回答。</p>}{answers.map((a,i)=><details className="spaced" key={a.question+i}><summary>{a.question}</summary><p className="smalltext">{a.answer}</p><button className="textbutton" onClick={()=>{setQuestion(a.question);setAnswer(a.answer);}}>编辑</button></details>)}</section>
 <section className="panel spaced"><h3>成功回执带回进度表</h3><p>扩展点击提交后先记为“待核实”。你确认看到成功页面或邮件，再导出回执文件到这里。</p><button className="secondary" onClick={()=>receiptFile.current.click()}><Upload size={16}/>导入投递回执</button><input ref={receiptFile} type="file" accept=".json" hidden onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000)throw Error('回执文件过大。');const payload=JSON.parse(await f.text());setData(importApplicationEvents(latest.current,payload));message('回执已合并；重复导入不会重复计数。只有你确认的成功回执才会标记 Applied。');}catch(e){message(e);}}}/>{jobs.filter(j=>!j.duplicateOf&&j.applicationEvents?.length).slice(0,10).map(j=><p className="smalltext" key={j.id}><Check size={13}/> {j.company} · {j.applicationEvents.at(-1).status} · <button className="textbutton" onClick={()=>onOpen(j.id)}>查看记录</button></p>)}</section></aside></div></>;
}
