'use client';
import {useState} from 'react';
import {RefreshCw,ArrowUpRight,CheckCircle2,AlertCircle,Clock,FileText} from 'lucide-react';

export function VisaBadge({visa}){const v=visa||{};return <div className="tags visa-tags"><span className={v.cpt?.status==='excluded'?'badtag':''}>CPT: {v.cpt?.status||'unknown'}</span><span className={v.future?.status==='unavailable'?'badtag':''}>Future sponsor: {v.future?.status||'unknown'}</span></div>}
export function UpdatesPanel({data,onOpen,onReviewed,refresh,busy,local}){
 const [filter,setFilter]=useState('All changes'),[requestNote,setRequestNote]=useState('');const catalog=data.catalogue||{},sources=catalog.sources||[];
 const changed=data.jobs.filter(j=>!j.duplicateOf&&j.scopeStatus!=='outside-target'&&j.catalogChangedAt&&(!j.reviewedAt||j.catalogChangedAt>j.reviewedAt)&&(filter!=='New only'||j.catalogChange==='new')).sort((a,b)=>(b.catalogChangedAt||'').localeCompare(a.catalogChangedAt||''));
 const schedule=catalog.schedule||{};
 return <><div className="sectionhead"><div><h2>New jobs & changes</h2><p className="muted">A fresh source catalogue, with your application history preserved.</p></div><button className="primary" disabled={busy} onClick={local?refresh:async()=>{try{await navigator.clipboard.writeText('请更新 Summer 2027 岗位，并更新我的私密求职系统。仅处理新增和变更岗位，保留投递记录。');setRequestNote('更新指令已复制。回到这个 Codex 任务粘贴发送后，才会执行更新。');}catch{setRequestNote('请在这个 Codex 任务回复“更新岗位”，再执行本次更新。');}}}><RefreshCw size={16}/>{busy?'Checking sources…':local?'确认更新本机岗位':'复制更新指令'}</button></div>
 <p className="muted smalltext">{requestNote||'本机按钮只在你确认后运行公共来源脚本，不调用模型。私密网页复制更新指令后，需要你在 Codex 发送，才会开始研究并发布。'}</p><div className="sourcegrid"><section className="panel"><span className="eyebrow">EVERY THREE DAYS</span><h3>{schedule.mode==='reminder-only'?'仅提醒，你决定是否更新':'Schedule status pending'}</h3><p>{schedule.display||'每三天提醒；未经确认不更新。'}</p><p className="smalltext muted">Last successful catalogue: {catalog.updatedAt?new Date(catalog.updatedAt).toLocaleString():'Not yet loaded'}<br/>Windows 本地提醒需要电脑开机且已登录；Codex 定时唤醒已暂停。提醒不调用模型。最近发布的岗位目录仍可照常查看。</p></section><section className="panel"><span className="eyebrow">EVIDENCE LEVELS</span><h3>{catalog.summary?.officialTargetDescriptions??0} target leads with employer descriptions</h3><p>{catalog.summary?.summer2027US??0} distinct US Summer 2027 target leads before personal eligibility checks.</p><p className="smalltext muted">{catalog.summary?.employerSummaryTargetLeads??0} additional target leads have researched employer summaries; {catalog.summary?.communityTargetLeads??0} have community/card evidence. These still need the complete JD. Community season labels are not employer confirmation. General 2027 programs, closed listings, duplicate aliases and other disciplines remain inspectable in All records.</p></section></div>
 <div className="sectionhead spaced"><h3>{changed.length} unreviewed changes</h3><select aria-label="Change filter" value={filter} onChange={e=>setFilter(e.target.value)}><option>All changes</option><option>New only</option></select></div>
 <div className="update-list">{changed.slice(0,80).map(j=><div className="panel updaterow" key={j.id}><div><span className="badge">{j.catalogChange==='new'?'NEW':'UPDATED'}</span><button className="jobtitle" onClick={()=>onOpen(j.id)}>{j.company} · {j.title}</button><small className="muted">{j.location} · {j.sourceState} · {j.catalogChangedAt?.slice(0,10)}</small></div><button className="secondary" onClick={()=>onReviewed(j.id)}>Mark reviewed</button></div>)}</div>{changed.length>80&&<p className="muted">Showing the latest 80. Use Opportunities filters to search the complete catalogue.</p>}{!changed.length&&<div className="panel empty"><CheckCircle2/><h3>You're caught up</h3><p>New or changed records will appear after the next successful refresh.</p></div>}
 <section className="panel spaced"><h3>Source health</h3><p className="muted">{sources.filter(s=>s.status==='ok').length} successful · {sources.filter(s=>s.status==='partial').length} partial · {sources.filter(s=>s.status==='failed').length} failed. Failed requests retain previous evidence.</p><div className="healthtable"><table><thead><tr><th>Source</th><th>Status</th><th>Returned</th><th>Last success / issue</th></tr></thead><tbody>{[...sources].sort((a,b)=>(a.status==='ok'?1:0)-(b.status==='ok'?1:0)).map(s=><tr key={s.id}><td><a href={s.url} target="_blank" rel="noreferrer">{s.name} <ArrowUpRight size={13}/></a><small>{s.kind}</small></td><td><span className={`badge ${s.status==='failed'?'badtag':''}`}>{s.status}</span></td><td>{s.count??0}{s.failedJobs?` / ${s.failedJobs} failed`:''}</td><td><small>{s.lastSuccessAt?.slice(0,16)||'No successful check recorded'}</small>{s.error&&<small className="danger">{s.error}</small>}</td></tr>)}</tbody></table></div></section></>;
}
export function PreparationPanel({job,onUpdate}){
 const fields=[['resume','Chosen the right resume version'],['eligibility','Reviewed CPT, future sponsorship and graduation wording'],['questions','Prepared role-specific answers'],['documents','Checked required documents / transcript']];
 return <><h3 className="spaced">Application checklist</h3><div className="preparation">{fields.map(([key,label])=><label key={key}><input type="checkbox" checked={!!job.preparation?.[key]} onChange={e=>onUpdate({preparation:{...job.preparation,[key]:e.target.checked}})}/>{label}</label>)}</div><div className="formgrid"><label>OA due date<input type="date" value={job.oaDue||''} onChange={e=>onUpdate({oaDue:e.target.value})}/></label><label>Interview date<input type="date" value={job.interviewDate||''} onChange={e=>onUpdate({interviewDate:e.target.value})}/></label><label>Resume / material version<input value={job.materialLabel||''} onChange={e=>onUpdate({materialLabel:e.target.value})} placeholder="AIE resume · September 2026"/></label></div></>;
}
export function AnswerLibrary({answers,onChange,onCopy}){return <section className="panel spaced"><h3>Reusable application answers</h3><p className="muted">Keep your own approved wording here. Review each application's exact question.</p>{[['availability','Availability and dates'],['authorization','Work authorization explanation'],['project','Strongest project pitch'],['motivation','Why this role / company']].map(([key,label])=><label className="spaced" key={key}>{label}<textarea rows={3} value={answers?.[key]||''} onChange={e=>onChange({...answers,[key]:e.target.value})}/><button className="textbutton" onClick={()=>onCopy(answers?.[key]||'')}>Copy answer</button></label>)}</section>}
export function NextActions({jobs,onOpen}){
 const today=new Date().toISOString().slice(0,10);const actions=jobs.filter(j=>!j.duplicateOf&&!['Rejected','Withdrawn','Archived'].includes(j.status)).flatMap(j=>[['OA deadline',j.status==='OA received'?j.oaDue:null],['Interview',j.interviewDate],['Follow-up',j.followUp]].filter(([,date])=>date).map(([kind,date])=>({j,kind,date}))).sort((a,b)=>a.date.localeCompare(b.date));
 return <section className="panel spaced"><h3>Next actions</h3>{actions.length?actions.slice(0,12).map(({j,kind,date})=><button className={`actionrow ${date<today?'danger':''}`} key={j.id+kind} onClick={()=>onOpen(j.id)}><Clock size={16}/><span>{date} · {kind}<b>{j.company} · {j.title}</b></span><ArrowUpRight size={15}/></button>):<p className="muted">Add OA deadlines, interview dates or follow-ups to put them here.</p>}</section>
}
