import {visaSignals} from './visa.mjs';
export const STATUSES=['Not started','Shortlisted','Draft ready','Applied','OA received','OA completed','Interview','Offer','Rejected','Withdrawn','Archived'];
const DICT={Python:['python'],PyTorch:['pytorch'],TensorFlow:['tensorflow'],SQL:['sql'],PostgreSQL:['postgresql','postgres'],Java:['java'], 'C++':['c++','c/c++'],RAG:['rag','retrieval augmented','retrieval-augmented'],LLM:['llm','large language model','foundation model'],LoRA:['lora','peft'],DeepSpeed:['deepspeed'],FAISS:['faiss'],Embeddings:['embedding'],Transformer:['transformer'],CNN:['cnn','convolutional'],LSTM:['lstm'],'Time series':['time series','forecasting'],NLP:['nlp','natural language'], 'Machine learning':['machine learning','machine-learning'], 'Deep learning':['deep learning'], 'Distributed training':['distributed training','multi-gpu','multi gpu','zero-3'],Evaluation:['evaluation','benchmark'], 'Data engineering':['data pipeline','data curation','data cleaning'],Docker:['docker'],Kubernetes:['kubernetes','k8s'],AWS:['aws','amazon web services'],Azure:['azure'],GCP:['gcp','google cloud'], 'CI/CD':['ci/cd','continuous integration'],JavaScript:['javascript'],TypeScript:['typescript'],React:['react'], 'Node.js':['node.js','nodejs'],Go:['golang','go'],GraphQL:['graphql'],API:['api','apis'],Git:['git'],Testing:['unit test','testing'], 'Data structures':['data structures'],Algorithms:['algorithms'], 'System design':['system design'],Recommendation:['recommendation','ranking','recommender'], 'ML serving':['model serving','model deployment','mlops'],Statistics:['statistics','statistical'],Mathematics:['mathematical','mathematics','linear algebra']};
const esc=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const PATTERNS=Object.entries(DICT).map(([skill,words])=>[skill,words.map(w=>new RegExp(`(^|[^a-z0-9])${esc(w)}(?:s)?(?=$|[^a-z0-9])`,'i'))]);
export function skillsIn(text=''){const t=String(text);return PATTERNS.filter(([,patterns])=>patterns.some(re=>re.test(t))).map(([skill])=>skill);}
const evidenceCache=new WeakMap();
function evidenceFor(profile,skill){let map=evidenceCache.get(profile);if(!map){map=new Map();for(const e of profile.evidence||[])for(const s of new Set([...skillsIn((e.skills||[]).join(' ')),...(e.skills||[])])){const key=s.toLowerCase();map.set(key,[...(map.get(key)||[]),e]);}evidenceCache.set(profile,map);}return map.get(skill.toLowerCase())||[];}
export function safeUrl(value){if(!value)return '';try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();return u.href;}catch{throw Error('Use a valid http(s) job URL.');}}
export function canonicalUrl(url){if(!url)return '';const u=new URL(safeUrl(url));['utm_source','utm_medium','utm_campaign','utm_content','utm_term','trk','trackingId','refId','gh_src','source'].forEach(k=>u.searchParams.delete(k));if(['boards.greenhouse.io','job-boards.greenhouse.io'].includes(u.hostname))u.hostname='job-boards.greenhouse.io';if(['jobs.lever.co','jobs.ashbyhq.com'].includes(u.hostname)){u.pathname=u.pathname.replace(/\/(apply|application)\/?$/,'');u.search='';}u.hash='';u.pathname=u.pathname.replace(/\/$/,'');return u.href;}
export function normalizeJob(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw)||!String(raw.title||'').trim())throw Error('A job title is required.');
 const text=String(raw.jd??raw.jdText??raw.summary??'').slice(0,60000),title=String(raw.title).slice(0,300),combined=`${title}\n${text}`;
 const termText=title+'\n'+text.split(/\n|(?<=[.!?])\s/).filter(s=>!/graduat|degree completion/i.test(s)).join('\n');
 const term=termText.match(/(summer|spring|fall|winter)\s*(?:of\s*)?(202[6-9])|(202[6-9])\s*[-–:]?\s*(summer|spring|fall|winter)/i);
 const inferredYear=Number(term?.[2]||term?.[3]||title.match(/\b202[6-9]\b/)?.[0])||null;
 const year=raw.year===null&&raw.yearBasis==='employer-year-unconfirmed'?null:Number(raw.year)||inferredYear;
 const season=raw.season==='Unknown'&&raw.yearBasis==='employer-year-unconfirmed'?'Unknown':raw.season&&raw.season!=='Unknown'?raw.season:term?(term[1]||term[4]).replace(/^./,c=>c.toUpperCase()):(/summer/i.test(termText)?'Summer':/spring/i.test(termText)?'Spring':/fall|autumn/i.test(termText)?'Fall':'Unknown');
 const tracks=Array.isArray(raw.tracks)?raw.tracks.filter(x=>['AIE','SDE','MLE'].includes(x)):[/machine learning|data scien/i.test(title)?'MLE':/\bai\b|llm|generative/i.test(title)?'AIE':'SDE'];
 const url=safeUrl(raw.url||'');
 return {...raw,id:String(raw.id||`job-${Date.now()}-${Math.random().toString(36).slice(2,8)}`),title,company:String(raw.company||'Company to confirm').slice(0,200),location:String(raw.location||'Location to confirm').slice(0,250),url,jd:text,year,season,tracks,status:STATUSES.includes(raw.status)?raw.status:'Not started',source:raw.source||raw.sourceType||(url.includes('linkedin.com')?'LinkedIn':url.includes('joinhandshake.com')?'Handshake':'Manual import'),checkedAt:raw.checkedAt||null,deadline:raw.deadline||'',notes:String(raw.notes||'').slice(0,20000),history:Array.isArray(raw.history)?raw.history:[],sources:Array.isArray(raw.sources)?raw.sources.filter(s=>{try{return !!safeUrl(s.url)}catch{return false}}):(url?[{title:raw.source||'Job listing',url}]:[])};
}
export function matchJob(job,profile,today=new Date().toISOString().slice(0,10)){
 const text=String(job.jd??job.summary??''),full=`${job.title||''}\n${job.degree||''}\n${job.authorization||''}\n${text}`;
 const checks=[];const check=(key,status,message)=>checks.push({key,status,message});
 const internship=/\bintern(?:ship)?\b|\bco[ -]?op\b/i.test(job.title||'')||/^internship|^intern$/i.test(job.employmentType||'');
 if(!internship)check('job-type',/full[ -]?time|permanent/i.test(job.employmentType||'')||/new grad|graduate engineer|senior|staff engineer/i.test(job.title||'')?'blocked':'review','Only internships/co-ops are in scope; confirm the employment type.');
 if(!job.country||job.country==='Unconfirmed')check('location','review','Confirm that this internship is located in the United States.');
 if(job.scopeStatus==='outside-target')check('track','blocked','This record is outside AIE, SDE and MLE target roles.');
 if(job.country&& !['US','USA','United States','Unconfirmed'].includes(job.country))check('country','blocked','This role is outside the confirmed US search scope.');
 check('season',job.year===2027&&job.season==='Summer'?'pass':job.year&&job.year!==2027||job.season&& !['Summer','Unknown'].includes(job.season)?'blocked':'review',job.year===2027&&job.season==='Summer'?'Summer 2027 identified.':'Confirm exact internship year and season.');
 if(job.deadline&&job.deadline.slice(0,10)<today)check('deadline','blocked','The recorded deadline has passed.');
 if(job.openStatus==='Closed'||['closed','unlisted'].includes(job.sourceState))check('availability','blocked','Source reports a closed or unavailable role.');
 const degreeLines=full.split(/[\n;]|(?<=\.)\s/).filter(l=>/ph\.?d/i.test(l));
 const phd=(/\bph\.?d\b/i.test(job.title||'')&&!/\bms\b|m\.s\.|master|bachelor|\bbs\b/i.test(job.title||''))||degreeLines.some(l=>/ph\.?d\.?\s*(?:degree\s*)?(required|only)|(?:pursuing|enrolled in|current).{0,60}ph\.?d/i.test(l)&&!/(?:ms|m\.s\.|master|bachelor|bs|b\.s\.).{0,35}(?:or|\/|and).{0,20}ph\.?d|ph\.?d.{0,25}(?:or|\/|and).{0,20}(?:ms|master|bachelor|bs)/i.test(l)&&!/preferred|nice.to.have/i.test(l));
 if(phd)check('degree',profile.degree==='phd'?'pass':!profile.degree||profile.degree==='unknown'?'review':'blocked','This role requires a PhD.'); else check('degree','review',`Check eligible degree/major against your ${profile.degree||'unconfirmed'} program; degree titles alone do not establish equivalence.`);
 const citizen=/(?:u\.?s\.?|united states) citizen(?:ship)?.{0,20}(?:required|must)|(?:must|require).{0,30}(?:u\.?s\.?|united states) citizen/i.test(full);
 if(citizen)check('citizenship',profile.citizenship==='yes'?'pass':profile.citizenship==='no'?'blocked':'review','US citizenship is required; verify your eligibility.');
 if(/security clearance|secret clearance/i.test(full))check('clearance','review','Security clearance eligibility needs verification.');
 const visa=visaSignals(job);
 if(visa.cpt.status==='excluded'&&profile.visaStatus==='F-1')check('cpt','blocked','Employer excludes F-1/CPT candidates. '+visa.cpt.evidence);
 else check('cpt',visa.cpt.status==='accepted'&&profile.authorization==='yes'?'pass':'review',visa.cpt.status==='accepted'?'Employer mentions CPT acceptance; confirm the exact dates with your school.':'Confirm your internship authorization and employer acceptance separately.');
 if(visa.usPerson.status==='required')check('us-person',profile.visaStatus==='F-1'?'blocked':'review','The role requires US-person status under export controls.');
 if(visa.future.status==='unavailable')check('sponsorship',profile.sponsorship==='yes'?'blocked':'review','Future sponsorship restriction: '+visa.future.evidence);
 else if(visa.future.status==='available')check('sponsorship','review','Employer states sponsorship support; confirm it applies to this internship and later conversion.');
 else check('sponsorship','review','Future sponsorship is not confirmed. '+(visa.current.evidence||''));
 if(profile.authorization==='no'&&/work authorization required|must be (?:legally )?authorized|legal.{0,15}work authorization required/i.test(full))check('authorization','blocked','You indicated that you do not meet the stated work authorization requirement.');
 else if(profile.authorization!=='yes')check('authorization','review','Your internship work authorization has not been confirmed.');
 if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(profile.graduation||''))check('graduation','review','Confirm your expected graduation month and year.');
 else if(job.graduationMin&&profile.graduation<job.graduationMin||job.graduationMax&&profile.graduation>job.graduationMax)check('graduation','blocked','Your graduation date is outside the stated window.');
 else if(job.graduationMin||job.graduationMax)check('graduation','pass',`Expected graduation ${profile.graduation} is within the recorded window.`);
 else check('graduation','review','Confirm graduation window and return-to-school requirement.');
 if(!job.checkedAt||job.sourceState==='indexed'||job.sourceState==='summary')check('source','review','Read the current full JD and application form before applying.');
 let tier='required';const groups=[],unscored=[];
 function addGroup(label,t){const tokens=skillsIn(label);if(!tokens.length){if(label.trim()&&job.requirementsClassified)unscored.push(label);return;}const any=/\bor\b|one of|such as|examples:/i.test(label);if(any)groups.push({label,tier:t,tokens,any:true});else for(const skill of tokens)groups.push({label:skill,tier:t,tokens:[skill],any:false});}
 if(job.requirementsClassified&&Array.isArray(job.requiredSkills)){job.requiredSkills.forEach(l=>addGroup(l,'required'));(job.preferredSkills||[]).forEach(l=>addGroup(l,'preferred'));}
 else for(const line of text.split(/\n|(?=preferred qualifications:)|(?=minimum qualifications:)|[;]|(?<=\.)\s/i)){if(/preferred|nice.to.have|bonus|a plus/i.test(line))tier='preferred';if(/minimum qualifications|required qualifications|requirements:/i.test(line))tier='required';addGroup(line,tier);}
 const matched=[],missingRequired=[],missingPreferred=[],seen=new Set();
 for(const g of groups){const results=g.tokens.map(skill=>{const ev=evidenceFor(profile,skill);return {skill,ev,strength:ev.length?(ev.some(e=>e.kind!=='listed')?1:.6):0};});g.credit=Math.max(...results.map(r=>r.strength));for(const r of results){if(r.ev.length&&!seen.has(g.tier+r.skill)){matched.push({skill:r.skill,tier:g.tier,evidence:r.ev.map(e=>({id:e.id,title:e.title,body:e.body,source:e.source})),strength:r.strength});seen.add(g.tier+r.skill);}if(!r.ev.length&&!(g.any&&g.credit>0)){const missing=g.tier==='required'?missingRequired:missingPreferred;const label=g.any?g.tokens.join(' or '):r.skill;if(!missing.includes(label))missing.push(label);}}}
 const required=groups.filter(g=>g.tier==='required'),preferred=groups.filter(g=>g.tier==='preferred');
 const coverage=list=>list.length?list.reduce((s,g)=>s+g.credit,0)/list.length:0;
 const score=required.length||preferred.length?Math.round(required.length&&preferred.length?80*coverage(required)+20*coverage(preferred):100*coverage(required.length?required:preferred)):null;
 const eligibility=checks.some(c=>c.status==='blocked')?'blocked':checks.some(c=>c.status==='review')?'review':'pass';
 return {visa,score,required,preferred,matched,missingRequired,missingPreferred,unscored,checks,eligibility,priority:eligibility==='blocked'?'Do not prioritize':score===null?'Read full JD':score>=70?'Review & shortlist':score>=40?'Targeted preparation':'Lower evidence coverage',basis:job.jdTextKind||'Keyword and project evidence coverage; verify requirement wording and alternatives.'};
}
export function mergeJobs(existing,incoming){const result=existing.map(x=>({...x}));for(const raw of incoming){const j=normalizeJob(raw);const idx=result.findIndex(e=>e.id===j.id||(e.url&&j.url&&canonicalUrl(e.url)===canonicalUrl(j.url)));if(idx<0)result.push(j);else{const old=result[idx];const newer=(j.checkedAt||'')>=(old.checkedAt||'')&&!!j.jd;const merged=newer?{...old,...j}:{...j,...old};if(newer&&j.jd!==old.jd){const factKeys=['degree','graduation','graduationMin','graduationMax','authorization','deadline','requiredSkills','preferredSkills','requirementsClassified'];merged.previousFacts=[...(old.previousFacts||[]),Object.fromEntries(['checkedAt','jd',...factKeys].map(k=>[k,old[k]]))];for(const key of factKeys)merged[key]=raw[key];}for(const key of ['id','status','notes','history','appliedAt','oaReceivedAt','oaCompletedAt','interviewAt','offerAt','followUp','oaDue','interviewDate','packetVersions','draftPacket','preparation','manualFields','materialLabel','reviewedAt'])if(old[key]!==undefined)merged[key]=old[key];merged.sources=[...new Map([...(old.sources||[]),...(j.sources||[])].map(s=>[s.url,s])).values()];result[idx]=merged;}}return result;}
export function transitionJob(job,status,at=new Date().toISOString()){if(!STATUSES.includes(status))throw Error('Invalid application status.');const dateKey={'Applied':'appliedAt','OA received':'oaReceivedAt','OA completed':'oaCompletedAt','Interview':'interviewAt','Offer':'offerAt'}[status];return {...job,status,...(dateKey?{[dateKey]:job[dateKey]||at}:{}),history:[...(job.history||[]),{at,from:job.status||'Not started',to:status}]};}
export function makePacket(job,profile,track='AIE'){
 const skills=skillsIn(job.jd||job.summary||'');const evidences=[...(profile.evidence||[])].filter(e=>e.kind!=='listed').map(e=>({e,n:(e.skills||[]).filter(s=>skills.includes(s)).length})).sort((a,b)=>b.n-a.n).slice(0,3).map(x=>x.e);
 const focus={AIE:'LLM adaptation, retrieval and evaluation',MLE:'model training, forecasting and reproducible evaluation',SDE:'backend workflows, relational databases and data-intensive applications'}[track]||'AI engineering';
 return `${profile.name}\n${job.company} — ${job.title}\n\nPROFILE\n${profile.school||'Carnegie Mellon University'} master's student, expected ${profile.graduation}. Focus: ${focus}.\n\nRELEVANT EXPERIENCE\n${evidences.map(e=>`${e.title}\n• ${e.body}`).join('\n\n')}\n\nWHY THIS ROLE — DRAFT\nI am interested in the ${job.title} opportunity at ${job.company}. My background combines applied mathematics and hands-on experience in ${focus}. ${evidences[0]?.body||''} I would welcome the opportunity to bring this experience to the team.\n\nREVIEW BEFORE USE\nConfirm availability, degree eligibility, work authorization and sponsorship answers. Review each claim and add your verified project links. This packet has not been submitted.`;
}
export function csvExport(jobs){const cols=['company','title','tracks','status','deadline','location','url','source','checkedAt','appliedAt','oaReceivedAt','oaCompletedAt','oaDue','interviewDate','followUp','materialLabel','notes'];const cell=v=>'"'+String(Array.isArray(v)?v.join(' / '):v??'').replace(/^(\s*[=+@-])/,"'$1").replace(/"/g,'""')+'"';return '\uFEFF'+[cols.join(','),...jobs.map(j=>cols.map(k=>cell(j[k])).join(','))].join('\r\n');}
